name: isilahtitiktitik
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  integration_test:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  intl: ^0.18.0
  http: ^1.1.0
  rxdart: ^0.27.4
  shimmer: ^3.0.0
  provider: ^6.0.3
  google_fonts: ^5.1.0
  flutter_bloc: ^8.0.1
  url_launcher: ^6.1.2
  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.15
  permission_handler: ^10.1.0
  cached_network_image: ^3.2.1
  flutter_local_notifications: ^15.1.0+1
  firebase_messaging: ^14.1.2
  firebase_core: ^2.3.0
  flutter_password_strength: ^0.1.6
  flutter_html:
    git:
      url: https://github.com/onhiw/flutter_html.git
      ref: master
  expandable: ^5.0.1
  flutter_inappwebview: ^5.5.0+2
  another_flushbar: ^1.10.29
  image_picker: ^1.0.2
  pinput: ^3.0.0
  package_info_plus: ^4.1.0
  google_sign_in: ^6.1.4
  connectivity_plus: ^4.0.1
  flutter_radar_chart:
    git:
      url: https://github.com/onhiw/flutter_radar_chart.git
      ref: master
  share_plus: ^7.1.0
  lottie: ^2.6.0
  flame: ^1.8.2
  hive: ^2.2.3
  path_provider: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  badges: ^3.1.1
  duration: ^3.0.11
  flutter_animation_progress_bar: ^2.2.1
  youtube_player_iframe: ^4.0.4
  logger: ^2.0.1
  file_picker: ^5.2.1
  flutter_spinkit: ^5.1.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  unique_identifier: ^0.3.0
  percent_indicator: ^4.2.3
  just_the_tooltip: ^0.0.12
  just_audio: ^0.9.34
  dio_http_cache: ^0.3.0
  encrypt: ^5.0.1
  crypto: ^3.0.3

dev_dependencies:
  hive_generator: 1.1.3
  build_runner: 2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.9.0

dependency_overrides:
  firebase_messaging_platform_interface: 4.2.7

flutter_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo_isilah_ios.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/logo/
    - assets/gif/
    - assets/images/
    - assets/audio/
    - assets/game/UI/

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Italic.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
    - family: LapsusProBold
      fonts:
        - asset: assets/fonts/lapsus-pro.bold.otf
